spring:
  application:
    name: midnight-sharding
  sharding:
    datasources:
      ds0:
        url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds1:
        url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456


mybatis:
  #  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.midnight.sharding.demo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 5000
